spring:
  application.name: mvc-example
  profiles.active: ${MVC_ACTIVE_PROFILE:dev}
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    basename: messages
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password:
  h2:
    console:
      enabled: true
logging:
  file: logs/mvc_dev.log
  level:
    org.springframework.web: DEBUG
    ru.javazen.telegram.bot: DEBUG
    org.hibernate: DEBUG
---
spring:
  profiles: production
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${MVC_DB_CONNECTION_URL}
    username: ${MVC_DB_USER}
    password: ${MVC_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  file: logs/mvc_prod.log
  level:
    org.springframework.web: WARN
    ru.javazen.telegram.bot: WARN
    org.hibernate: WARN